force-app/main/default/objects/ObjectA__c/ObjectA__c.object-meta.xml
<CustomObject>
    <label>ObjectA</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ObjectsA</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ObjectB__c/ObjectB__c.object-meta.xml
<CustomObject>
    <label>ObjectB</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ObjectsB</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ObjectB__c/fields/ObjectA__c.field-meta.xml
<CustomField>
    <fullName>ObjectA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ObjectA</label>
    <referenceTo>ObjectA__c</referenceTo>
    <relationshipLabel>ObjectsB</relationshipLabel>
    <relationshipName>ObjectsB</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ObjectC__c/ObjectC__c.object-meta.xml
<CustomObject>
    <label>ObjectC</label>
    <nameField>
        <label>ObjectC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ObjectsC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ObjectC__c/fields/ObjectB__c.field-meta.xml
<CustomField>
    <fullName>ObjectB__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ObjectB</label>
    <referenceTo>ObjectB__c</referenceTo>
    <relationshipLabel>ObjectsC</relationshipLabel>
    <relationshipName>ObjectsC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CustomRelatedListControllerTest.cls
/**
 *
 *
 * @author: Thiago Barbosa
 *
 * @Description: CustomRelatedListControllerTest Controller  
 */

@isTest
public with sharing class CustomRelatedListControllerTest {
    



    @TestSetup
    static void createdData(){
        ObjectA__c objectA = new ObjectA__c();
        objectA.Name = 'TestNameA';
        Database.insert(objectA);

        ObjectB__c objectB = new ObjectB__c();  
        objectB.Name = 'TestNameB';
        objectB.ObjectA__c = objectA.Id;
        Database.insert(objectB);

        ObjectC__c objectC = new ObjectC__c();
        objectC.Name = 'TestNameC'; 
        objectC.ObjectB__c = objectB.Id; 
        Database.insert(objectC);

    }


    @isTest static void testfetchData(){ 

        ObjectB__c objectB =  [SELECT Id FROM ObjectB__c LIMIT 1];

        ObjectC__c objectC =  [SELECT Id FROM ObjectC__c LIMIT 1];

        Test.startTest();
        CustomRelatedListController.ComponentInfo componentInfo = new CustomRelatedListController.ComponentInfo(); 
        componentInfo.pageNumber = 1;
        componentInfo.recordToDisplay = 10;
        componentInfo.objectType = 'ObjectC__c';
        componentInfo.parentField = 'ObjectB__c'; 
        componentInfo.parentRecordId = objectB.Id;
        componentInfo.recordId = objectC.Id;  

        CustomRelatedListController.ObjectWrapper wrapper = CustomRelatedListController.fetchData(JSON.serialize(componentInfo)); 
        Test.stopTest(); 
        System.assert(wrapper != null, 'Wrapper is different of null');
    }


    @isTest static void testDeleteData(){ 

        ObjectB__c objectB =  [SELECT Id FROM ObjectB__c LIMIT 1];

        ObjectC__c objectC =  [SELECT Id FROM ObjectC__c LIMIT 1];

        try{
        Test.startTest();
        CustomRelatedListController.ComponentInfo componentInfo = new CustomRelatedListController.ComponentInfo(); 
        componentInfo.pageNumber = 1;
        componentInfo.recordToDisplay = 10;
        componentInfo.objectType = 'ObjectC__c';
        componentInfo.parentField = 'ObjectB__c';
        componentInfo.parentRecordId = objectB.Id;
        componentInfo.recordId = objectC.Id;   

        CustomRelatedListController.ObjectWrapper wrapper = CustomRelatedListController.deleteRecord(JSON.serialize(componentInfo)); 
        Test.stopTest(); 
        System.assert(wrapper != null, 'Wrapper is different of null'); 
        }catch(Exception ex){  
            System.assert(ex.getMessage() != null);
        }
    }

}